// server/shared/roles.js
const ROLES = {
    DON: 'DON',
    UNDERBOSS: 'UNDERBOSS',
    BUSINESS_MANAGER: 'BUSINESS_MANAGER',
    GRH: 'GRH',
    GANG_SUPERVISOR: 'GANG_SUPERVISOR',
    CHEF_BRAQUAGE: 'CHEF_BRAQUAGE',
    SOLDAT: 'SOLDAT',
    GANG_MEMBER: 'GANG_MEMBER'
};

const ROLE_GROUPS = {
    DON_ONLY: [ROLES.DON],
    ORDER_APPROVERS: [ROLES.DON, ROLES.UNDERBOSS, ROLES.BUSINESS_MANAGER, ROLES.GRH, ROLES.CHEF_BRAQUAGE],
    SHOP_MANAGER: [ROLES.DON, ROLES.UNDERBOSS, ROLES.BUSINESS_MANAGER, ROLES.GANG_SUPERVISOR],
    GANG_MEMBER_ONLY: [ROLES.GANG_MEMBER],
    MEMBERS: Object.values(ROLES),
    ADMIN: [ROLES.UNDERBOSS, ROLES.BUSINESS_MANAGER, ROLES.GRH, ROLES.GANG_SUPERVISOR, ROLES.CHEF_BRAQUAGE],
    DON_AND_ADMIN: [ROLES.DON, ROLES.UNDERBOSS, ROLES.BUSINESS_MANAGER, ROLES.GRH, ROLES.GANG_SUPERVISOR, ROLES.CHEF_BRAQUAGE],
    DON_AND_SHOP: [ROLES.DON, ROLES.BUSINESS_MANAGER],
    ATTENDANCE_VIEW: [ROLES.DON, ROLES.UNDERBOSS, ROLES.BUSINESS_MANAGER, ROLES.GRH, ROLES.GANG_SUPERVISOR, ROLES.CHEF_BRAQUAGE]
};

module.exports = { ROLES, ROLE_GROUPS };
